// Whitelisted Vue routes
// everything else will be forwarded to the legacy client
// using the ./proxy.js serverMiddleware

const mongoId = "[a-z0-9]{24}";
const h5pId = "[a-z0-9]+";

const vueRoutes = [
	`^/favicon.png$`,
	`^/calendar/?$`,
	`^/collabora/doc.docx$`,
	`^/collabora/presentation.pptx$`,
	`^/collabora/spreadsheet.xlsx$`,
	`^/_nuxt/*`,
	`^/runtime.config.json`,
	`^/account/?$`,
	`^/account/teams/?$`,
	`^/account/thirdPartyProviders/?$`,
	`^/administration/?$`,
	`^/administration/students/?$`,
	`^/administration/students/new/?$`,
	`^/administration/students/consent/?$`,
	`^/administration/teachers/?$`,
	`^/administration/teachers/new/?$`,
	`^/administration/ldap/config/?$`,
	`^/administration/ldap/activate/?$`,
	`^/administration/school-settings/?$`,
	`^/administration/school-settings/tool-configuration/?$`,
	`^/administration/school-settings/tool-configuration/${mongoId}/?$`,
	`^/administration/school-settings/provisioning-options/?$`,
	`^/administration/migration/?$`,
	`^/administration/groups/classes/?$`,
	`^/administration/groups/classes/${mongoId}/?$`,
	`^/administration/rooms/new/?$`,
	`^/administration/rooms/manage/?$`,
	`^/administration/rooms/manage/${mongoId}?$`,
	`^/boards/${mongoId}/?$`,
	`^/boards/${mongoId}/cards/${mongoId}/?$`,
	`^/collabora/${mongoId}/?$`,
	`^/error/?$`,
	`^/h5p/player/${h5pId}/?$`,
	`^/h5p/editor/?$`,
	`^/h5p/editor/${h5pId}/?$`,
	`^/help/?$`,
	`^/help/articles/?$`,
	`^/help/contact/?$`,
	`^/help/confluence/[0-9]+/?$`,
	`^/help/faq/documents/?$`,
	`^/dashboard/?$`,
	`^/$`,
	`^/onboarding/?$`,
	`^/login/?$`,
	`^/logout/?$`,
	`^/imprint/?$`,
	`^/licenses/?$`,
	`^/legacy-view-migration/?$`,
	`^/migration/?$`,
	`^/migration/success/?$`,
	`^/migration/error/?$`,
	`^/media-shelf/?$`,
	`^/media-shelf/fwu-media/?$`,
	`^/news/?$`,
	`^/news/new/?$`,
	`^/news/${mongoId}/?$`,
	`^/news/${mongoId}/edit/?$`,
	`^/files/?$`,
	`^/files/my/?$`,
	`^/poc-files/?$`,
	`^/folder/${mongoId}/?$`,
	`^/folder/${mongoId}/trash/?$`,
	`^/rooms/invitation-link/${mongoId}?$`,
	`^/homework/${mongoId}/?$`,
	`^/rooms/?$`,
	`^/rooms/new/?$`,
	`^/rooms/${mongoId}/?$`,
	`^/rooms/${mongoId}/board/?$`,
	`^/rooms/${mongoId}/edit/?$`,
	`^/rooms/${mongoId}/members/?$`,
	`^/rooms/courses-list/?$`,
	`^/rooms/courses-overview/?$`,
	`^/rooms-overview/?$`,
	`^/system/releases/?$`,
	`^/system/security`,
	`^/tasks/?$`,
	`^/tools/context/tool-configuration/?$`,
	`^/tools/context/tool-configuration/${mongoId}/?$`,
	`^/registration-external-members/?$`,
	`^/@`,
	`^/src/`,
	`^/node_modules/`,
];

export const isVueClient = (path: string) => vueRoutes.some((regex) => new RegExp(regex).exec(path));
